repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: check-ast
    -   id: debug-statements
    -   id: name-tests-test
        args: [ --django ]
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
